version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=xlnudi+3x4z&bR6the_a
      - POSTGRES_DB=authdb
    ports:
      - 5436:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local